name: Deploy Nodejs Application to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: root
          key: ${{ secrets.SSH_KEY }}
          port: 22
          timeout: 60s
          command_timeout: 20m
          debug: true
          script: |
            cd /root/api-service
            git pull origin main
            docker compose down
            docker compose up -d --build